name = "DocumentationTest"
uuid = "1d910de4-5427-41e8-ba17-11e2efbf87b7"
authors = ["WhiffleFish <tylertronics@gmail.com>"]
version = "0.1.0"

[deps]
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
StaticArrays = "1.5"